apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bugsnag-maui
  annotations:
    github.com/project-slug: lampo/bugsnag-maui
spec:
  type: library
  lifecycle: production
  system: everydollar
  owner: ramsey-plus
